const { withPodfile } = require('@expo/config-plugins');

// Stage 5D.6C.
//
// Durably activates WalletCoreBridge's CocoaPods `test_spec` ("Tests") so
// `expo prebuild` / `pod install` produces a real, runnable XCTest target
// for it every time.
//
// Root cause this works around (verified against the installed
// expo-modules-autolinking@57.0.9 Ruby source, not assumed): Expo's
// autolinking only populates a pod's `:testspecs` option when the Podfile's
// `use_expo_modules!` call itself is invoked with `includeTests`/`testsOnly`
// — a call-site option, not something any per-module `expo-module.config.json`
// field or `Podfile.properties.json` key can set. Since `apps/mobile/ios` is
// fully regenerated by `expo prebuild` (not tracked — see root .gitignore),
// there is no durable, hand-editable Podfile to add this to directly; a
// config plugin is the smallest mechanism that survives regeneration.
//
// Scope, deliberately narrow: this inserts exactly one explicit
// `pod 'WalletCoreBridge', :path => ..., :testspecs => ['Tests']` line
// immediately before `use_expo_modules!`. Expo's autolinking loop skips
// re-adding any pod that is already an explicit target dependency, so this
// activates ONLY WalletCoreBridge's test spec — it does not set the global
// `includeTests`/`testsOnly` flag, does not affect any other Expo module,
// and does not touch signing, deployment target, build settings,
// entitlements, or capabilities. Idempotent: re-running prebuild does not
// duplicate the line.
const POD_LINE =
  "  pod 'WalletCoreBridge', :path => '../modules/wallet-core-bridge/ios', :testspecs => ['Tests']\n";

const USE_EXPO_MODULES_MARKER = 'use_expo_modules!';

function withWalletCoreBridgeTestSpec(config) {
  return withPodfile(config, (config) => {
    const { contents } = config.modResults;

    if (contents.includes("pod 'WalletCoreBridge'")) {
      // Already present (e.g. a second prebuild run) — nothing to do.
      return config;
    }

    const markerIndex = contents.indexOf(USE_EXPO_MODULES_MARKER);
    if (markerIndex === -1) {
      throw new Error(
        'withWalletCoreBridgeTestSpec: could not find "use_expo_modules!" in the generated Podfile — ' +
          'the Expo Podfile template this plugin depends on may have changed.'
      );
    }

    config.modResults.contents =
      contents.slice(0, markerIndex) + POD_LINE + contents.slice(markerIndex);

    return config;
  });
}

module.exports = withWalletCoreBridgeTestSpec;
